apiVersion: v2
name: conductor-data-provider
description: A freshly created template-script
version: 0.0.6

dependencies:
  - name: file-mover
    repository: "https://energinet-singularity.github.io/helm-registry/"
    version: 1.1.2
