# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: ghcr.io/energinet-singularity/conduck/energinet-singularity/conduck
  pullPolicy: IfNotPresent
  tag: "0.0.5"

# Setup PVC
conductorInputVolume: 
  persistentVolumeClaim:
    claimName: conductor-data-pvc

conductorDataVolume:
  accessMode: ReadWriteOnce
  size: 1G
  storageClass: standard

# Setup file-mover
file-mover:
  folderMounts:
    input:
      enabled: true
      volume:
        emptyDir: {}
    output:
      enabled: true
      volume:
        persistentVolumeClaim:
          claimName: conductor-data-pvc
  podLabels:
    fm-conductor-parser: "S1"
  selectorLabels:
    fm-conductor-parser: "S1"
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: conductor-fm-parser
                operator: In
                values:
                - S1
          topologyKey: "kubernetes.io/hostname"

# Setup affinity (including labels)
podLabels:
  conductor-fm-parser: "S1"
selectorLabels:
  conductor-fm-parser: "S1"
affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: fm-conductor-parser
              operator: In
              values:
              - S1
        topologyKey: "kubernetes.io/hostname"

# Environment variables
#api:
#  port: 5999
#  dbname: "othername"
#debug: "TRUE"
#mock_data: "TRUE"
#filepath:
#  dd20: "/other/place/file.xlsm"
#  dd20_mapping: "/this/place/file.xlsx"
#  mrid_mapping: "/new/place/file.csv"

#Default settings not used in this setup
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
podLabels: {}
selectorLabels: {}
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  
